services:
  pytwb:
    image: pytwb-image
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: humble
    network_mode: host
    ipc: host
    environment:
      - DISPLAY=:${DISPLAY}
    volumes:
      - ./pytwb:/usr/local/lib/pytwb/pytwb:rw
    command: sleep infinity

