services:
  pytwb:
    image: pytwb-image
    build:
      context: .
      dockerfile: pytwb_wb/Dockerfile
      args:
        ROS_DISTRO: humble
    network_mode: host
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
#    volumes:
# place existing package code here
#      - <path to package>:/root/pytwb_ws/src/<package name>:rw
    command: sleep infinity

